login_and_reg_button = ".//button[text()='Вход и регистрация']"
no_account_button = ".//button[text()='Нет аккаунта']"
input_for_email = ".//input[@name='email']"
input_for_password = ".//input[@name='password']"
input_for_repeat_password = ".//input[@name='submitPassword']"
create_account_button = ".//button[text()='Создать аккаунт']"
user_avatar = ".//button[@class='circleSmall']"
user_name = ".//h3[text()='User.']"
error_message = ".//div[@class='popUp_inputColumn__RgD8n']/div[1]/span"
div_for_email_input = ".//input[@name='email']/parent::div"
div_for_password_input = ".//input[@name='password']/parent::div"
div_for_repeat_password_input = ".//input[@name='submitPassword']/parent::div"
login_button = ".//button[text()='Войти']"
logout_button = ".//button[text()='Выйти']"
place_ad_button = ".//button[text()='Разместить объявление']"
modal_header = ".//div[@class='popUp_titleRow__M7tGg']/h1"
goods_name_input = ".//input[@name='name']"
goods_description_textarea = ".//textarea[@name='description']"
goods_price_input = ".//input[@name='price']"
dropdown_list_buttons = ".//button[@class='dropDownMenu_arrowDown__pfGL1 dropDownMenu_noDefault__wSKsP']"
books_category_button = ".//span[text()='Книги']/parent::button"
city_category_button = ".//span[text()='Санкт-Петербург']/parent::button"
radiobuttons_list = ".//div[@class='radioUnput_shell__Wtdwe']"
place_ad_submit_button = ".//button[text()='Опубликовать']"
user_profile_page_header = ".//h1[text()='Мой профиль']"
user_ads_header = ".//h1[text()='Мои объявления']"
placed_ad_name = ".//div[@class='card']/div/div[@class='about']/h2"
